{
 "title": "Auction API",
 "tags": [
  "auction",
  "take-home"
 ],
 "refresh": "5s",
 "panels": [
  {
   "title": "Bid accepted rate (per second)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "rate(auction_bids_accepted_total[1m])",
     "legendFormat": "accepted"
    }
   ]
  },
  {
   "title": "Bid rejected rate by reason (per second)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum by (reason) (rate(auction_bids_rejected_total[1m]))",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "HTTP latency p95 by route (5m window)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 24, "h": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, uri) (rate(http_server_requests_seconds_bucket[5m])))",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "HTTP latency avg by route (5m window)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 17, "w": 24, "h": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (uri) (rate(http_server_requests_seconds_sum[5m])) / sum by (uri) (rate(http_server_requests_seconds_count[5m]))",
     "legendFormat": "{{uri}}"
    }
   ]
  }
 ]
}